---
- name: Add test text file
  hosts: vmw-frclnp01
  gather_facts: false
  tasks:
    - name: Create ansadmuser home directory
      file:
        path: "/home/ansadmuser"
        state: directory
        mode: "0755"
        owner: ansadmuser
        group: ansadmuser
      become: true
      become_user: root

    - name: Add test text file
      lineinfile:
        line: "test"
        dest: "/home/ansadmuser/ansadmuser.txt"
        state: present
      become: true
      become_user: ansadmuser
