- hosts: vmw-frclnp01
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "create www directory"
    file:
      path: /var/www/maleo.com
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/maleo.com
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: Add entry to /etc/hosts
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: '127.0.0.1       maleo.com'

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted